version: '3'
services:
  hugo:
    image: klakegg/hugo:0.74.3-ubuntu
    volumes:
        - ".:/src"
    entrypoint: bash
    ports:
        - "1313:1313"
    tty: true
    working_dir: /src
    command: -c 'cd blog; hugo server'

  hugo-build:
    image: klakegg/hugo:0.74.3-ubuntu
    volumes:
        - ".:/src"
    working_dir: /src/blog
    entrypoint: hugo
    command: --minify