baseURL = 'https://20yuteo.com/hugoapp/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = '20yuteo.log'
theme = 'hugo-PaperMod'
publishDir = "../docs"
canonifyurls = true
enableEmoji = true


[author]
  name = "20yuteo"
  bio = ""
  job = "web enginner"
  location = "Japan Tokyo "
  email = "20yuteo@gmail.com"
  discribe = "test"

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  dateFormat = "2006-01-02"
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
  coverImage = "images/cover.jpg"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
  customCSS = ["/css/custom.css"]

[taxonomies]
  archive = "archives"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = ""